### ISSUE TITLE
ESM breaks `docusaurus-plugin-typedoc`

### ISSUE THREAD

**Issue by NanderTGA** [felipecrs/typedoc-plugin-rename-defaults#17]
I have no idea if this is something you can fix or even care about, but here goes.

I'm using Docusaurus for a documentation site.
This site uses [docusaurus-plugin-typedoc](https://www.npmjs.com/package/docusaurus-plugin-typedoc) to generate API docs, which uses [typedoc-plugin-markdown](https://www.npmjs.com/package/typedoc-plugin-markdown).
I configured Typedoc to use this plugin.

Recently, I migrated from Docusaurus v2 to v3, but this change had this weird side effect where the API docs would still get generated but Docusaurus wouldn't detect them until a rebuild is triggered by changing some file.
When I removed this plugin, the issue disappeared.
I tried using other plugins (and disabling all plugins) and the issue seems to be related to this plugin specifically.

Oh and before I forget: thanks a lot for making this plugin!

**Comment by felipecrs** [comment]
Hm... That's weird.

**Comment by felipecrs** [comment]
Any chance you can build a minimal repository where I can reproduce the issue?

**Comment by NanderTGA** [comment]
Sure, you can find it [here](https://github.com/NanderTGA/typedoc-plugin-rename-default-repro).

**Comment by felipecrs** [comment]
Thanks a lot. I can reproduce the issue indeed. I don't have any good ideas to debug this problem however, so I'm just trying some generic things.

For example, you mentioned this issue happened after upgrading docusaurus from v2 to v3. However, I tried downgrading docusaurus in your repro (including everything it carries like react and so), but I can still reproduce the issue with docusaurus v2 in your repro repo.

Have you upgraded something else in between? I'm trying to identify what upgrade exactly caused this problem.

**Comment by NanderTGA** [comment]
Strange... I'll take a look at the previous build artifacts and commit history and see if I can find anything.

**Comment by NanderTGA** [comment]
I checked before and after [the commit where I migrated to v3](https://github.com/NanderTGA/msgroom-orm/commit/68b9d1222006c90ed328ed6f65993a161c48d12c) and after the migration the problem appeared.

Are you sure you downgraded everything?
Here's a full list of dependencies changed with the upgrade:
| Package                       | Old Version | New Version |
| ----------------------------- | ----------- | ----------- |
| @docusaurus/core              | ^2.4.3      | ^3.0.0      |
| @docusaurus/preset-classic    | ^2.4.3      | ^3.0.0      |
| @docusaurus/remark-plugin-npm2yarn | ^2.4.3 | ^3.0.0      |
| @mdx-js/react                 | ^1.6.22     | ^3.0.0      |
| clsx                          | ^1.2.1      | ^1.2.1      |
| docusaurus-plugin-typedoc     | ^0.20.1     | ^0.21.0     |
| prism-react-renderer           | ^1.3.5      | ^2.3.0      |
| react                         | ^17.0.2     | ^18.2.0     |
| react-dom                     | ^17.0.2     | ^18.2.0     |
| remark-docusaurus-tabs        | ^0.2.0      | Removed|
| rimraf                        | ^5.0.1      | ^5.0.5      |
| typedoc                       | ^0.25.1     | ^0.25.3     |
| typedoc-plugin-markdown       | ^3.16.0     | ^3.17.1     |
| typedoc-plugin-rename-defaults | ^0.6.6      | ^0.7.0      |

| Dev Package                   | Old Version | New Version |
| ----------------------------- | ----------- | ----------- |
| @docusaurus/module-type-aliases | ^2.4.3     | ^3.0.0      |
| @docusaurus/tsconfig          | Added   | ^3.0.0      |
| @docusaurus/types             | Added   | ^3.0.0      |
| @types/react                  | Added   | ^18.2.38    |
| typescript                    | Added   | ^5.2.2      |

I'll try messing around a bit with the dependencies to see if anything else could be the cause.

**Comment by felipecrs** [comment]
Yes, here's how I downgraded:

- https://github.com/NanderTGA/typedoc-plugin-rename-default-repro/pull/1

And I can still reproduce the issue just fine.

**Comment by felipecrs** [comment]
Ok, I think I figured it out. The upgrade of `typedoc-plugin-rename-defaults` from 0.6.6 to 0.7.0 triggers the issue.

I can no longer reproduce the issue after downgrading it to 0.6.6.

I will investigate.

**Comment by NanderTGA** [comment]
For me the issue appeared after upgrading from 0.6.6 to 0.6.7.

**Comment by felipecrs** [comment]
Actually, specifically when upgrading from 0.6.6 to 0.6.7.

**Comment by felipecrs** [comment]
Ok, I was able to isolate the issue. What triggered this problem was the migration from commonjs to esm.

I cannot reproduce the issue with:

- https://github.com/felipecrs/typedoc-plugin-rename-defaults/pull/18

@Gerrit0, do you have any idea about why this happens? Maybe when the plugin is esm, typedoc loads it asynchronously while when it's commonjs it loads it more synchronously.

**Comment by felipecrs** [comment]
Some notes:

- Maybe typedoc loads plugins in a different order, for example commonjs ones first and esm ones after.
- I see that typedoc-plugin-markdown is still commonjs. Maybe upgrading it to esm would help as well.

**Comment by Gerrit0** [comment]
The cause of this is probably that the docusaurus plugin inappropriately handles promises. It sounds like it doesn't await something important, so it happens to work on the second import because it's cached

**Comment by NanderTGA** [comment]
The docs still seem to be generated the first time, the problem is that Docusaurus doesn't see the generated files for some reason.
I opened [an issue](https://github.com/tgreyuk/typedoc-plugin-markdown/issues/530) on the plugin's repo.

**Comment by felipecrs** [comment]
https://github.com/tgreyuk/typedoc-plugin-markdown/issues/530#issuecomment-1867090958
